const ACCESS_TOKEN_EXPIRES_IN =
  process.env.V2_ACCESS_TOKEN_EXPIRES_IN || "15m";

const REFRESH_TOKEN_TTL_DAYS = Number.parseInt(
  process.env.V2_REFRESH_TOKEN_TTL_DAYS || "30",
  10,
);

const ORDER_RESERVATION_TTL_MINUTES = Number.parseInt(
  process.env.ORDER_RESERVATION_TTL_MINUTES || "10",
  10,
);

const PAYMENT_WEBHOOK_SECRET =
  process.env.PAYMENT_WEBHOOK_SECRET || process.env.JWT_SECRET || "";

const QR_SIGNING_SECRET =
  process.env.QR_SIGNING_SECRET || process.env.JWT_SECRET || "";

module.exports = {
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_TTL_DAYS: Number.isNaN(REFRESH_TOKEN_TTL_DAYS)
    ? 30
    : REFRESH_TOKEN_TTL_DAYS,
  ORDER_RESERVATION_TTL_MINUTES: Number.isNaN(ORDER_RESERVATION_TTL_MINUTES)
    ? 10
    : ORDER_RESERVATION_TTL_MINUTES,
  PAYMENT_WEBHOOK_SECRET,
  QR_SIGNING_SECRET,
};
